CC=g++
CFLAGS=-c -g -fpermissive
LDFLAGS=
SOURCES=hiopl.cpp dbopl.cpp load.cpp  cpu.cpp   
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=load

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
