include Makefile_sources
CC=g++
CC=/opt/opendingux-toolchain/usr/bin/mipsel-linux-g++

CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o

CFLAGS=-c -DLINUX -I. -LSDL/lib
CFLAGS=-c -O3 -DLINUX -D__SDL_AUDIO__ -DOPENDINGUX -I. -I/opt/opendingux-toolchain/usr/include/ -L/opt/opendingux-toolchain/usr/lib/ -lSDL -lSDL_ttf -fpermissive 

CFLAGS_SDLVERS=-D__SDL12__
LDFLAGS=-L/opt/opendingux-toolchain/usr/lib/ -lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread 

#SOURCES=Machine.cpp  AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp SineOscillator.cpp SawOscillator.cpp  FuzzyPulseOscillator.cpp  TriangleOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp InputManager.cpp VCO.cpp Sequencer.cpp PulseOscillator.cpp WaveTableSineOscillator.cpp NoiseOscillator.cpp Biquad.cpp PatternSequencer.cpp AudioDriverSDL.cpp 

SOURCES= \
		AudioDriverSDL.cpp       \
		SYSTEMLINUX.cpp	       \
		$(SOURCES_PICOLOOP)	\
		$(SOURCES_PICOSYNTH) 	\
		$(SOURCES_PICODRUM) 	\
		$(SOURCES_DBOPL) 	\
		$(SOURCES_PBSYNTH)






OBJECTS=$(SOURCES:.cpp=.o)
DEPENDENCY=$(SOURCES:.cpp=.d)
EXECUTABLE=PatternPlayer.dge

all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE) 

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@


%.o : %.cpp 
	$(CC) $(CFLAGS_SDLVERS) $(CFLAGS) $< -o $@

# include all the dependency .d file into the makefile 
# it allow to match change in .h file
include ${DEPENDENCY}

# the .d file contain the dependency
%.d : %.cpp %.h
	$(CC) $(CFLAGS_SDLVERS) -I. -MM $< -o $@


# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) $(CFLAGS_SDLVERS) -I. -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) $(CFLAGS_SDLVERS) -I. -MM $< -o $@ 



clean:
	-rm -f $(OBJECTS) 
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
