#CC=g++-4.4
CC=g++
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP



CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb 
CFLAGS= -c -O3 -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive -pg
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive -pg -DDUMP_AUDIO=0
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive 
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1 -DFIXED
CFLAGS= -c -std=c++11 -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -D __RTMIDI__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1  -fpermissive
CFLAGS= -c -std=c++11 -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -D __RTMIDI__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1  -DDEBUGPRINTF -fpermissive
CFLAGS= -c -std=c++11 -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -D __RTMIDI__ -DPC_DESKTOP -ggdb                   -DDEBUGPRINTF -DSCREEN_MULT=2  -fpermissive


CFLAGS_SDLVERS=-D__SDL20__
CFLAGS= -c -std=c++11 -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -D __RTMIDI__ -DPC_DESKTOP -ggdb  ${CFLAGS_SDLVERS}                 -DDEBUGPRINTF -DSCREEN_MULT=2  -fpermissive

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL           -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -lpulse -lpulse-simple -ljack
LDFLAGS=-lasound -lSDL2 -lSDL2_ttf -lpthread -lpulse -lpulse-simple -ljack


OBJTOLINK=RtAudio.o
OBJTOLINK=RtAudio.o RtMidi.o

SOURCES=Machine.cpp Track.cpp AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp OneOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp Biquad.cpp PatternSequencer.cpp AudioDriverRTAudio.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp Effect.cpp EffectDelay.cpp SongSequencer.cpp WaveTableManager.cpp WaveTable.cpp Generator.cpp 


#Machine.cpp Track.cpp AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp OneOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp Biquad.cpp PatternSequencer.cpp AudioDriverRTAudio.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp Effect.cpp EffectDelay.cpp SongSequencer.cpp WaveTableManager.cpp WaveTable.cpp Generator.cpp 

# 		      Synth.cpp                \
#		      Instrument.cpp           \

SOURCES=PatternPlayer.cpp \
		      SDL_GUI.cpp              \
		      SYSTEMLINUX.cpp	       \
		      AudioEngine.cpp          \
		      AudioDriverRTAudio.cpp   \
		      Oscillator.cpp           \
		      OneOscillator.cpp        \
		      Biquad.cpp               \
		      AudioMixer.cpp           \
		      Wave.cpp Track.cpp       \
		      Machine.cpp              \
		      MonoMixer.cpp            \
		      InputManager.cpp         \
		      Filter.cpp               \
		      AMSynthLowPassFilter.cpp \
		      Effect.cpp               \
		      EffectDelay.cpp          \
		      EffectDisabled.cpp       \
		      WaveTableManager.cpp     \
		      WaveTable.cpp            \
		      Generator.cpp            \
		      PatternElement.cpp       \
		      Pattern.cpp              \
		      PatternReader.cpp        \
		      Sequencer.cpp            \
		      PatternSequencer.cpp     \
		      SongSequencer.cpp        \
		      NoteFreq.cpp             \
		      PitchBend.cpp            \
		      TweakableKnob.cpp	       \
		      UserInterface.cpp	       \
		      SysMutex.cpp	       \
		      MidiOutSystem.cpp	       \
		      MidiInSystem.cpp	       \
		      MachineCheck.cpp	       \
		      WaveFileWriter.cpp       \
		      Machine/Picosynth/PicosynthUserInterface.cpp \
		      Machine/Picosynth/PicosynthADSR.cpp        \
		      Machine/Picosynth/PicosynthVCO.cpp         \
		      Machine/Picosynth/PicosynthMachine.cpp     \
		      Machine/Picodrum/PicodrumUserInterface.cpp \
		      Machine/Picodrum/PicodrumVCO.cpp           \
		      Machine/Picodrum/PicodrumADSR.cpp          \
		      Machine/Picodrum/PicodrumMachine.cpp       \
		      Machine/Dbopl/DboplUserInterface.cpp \
		      Machine/Dbopl/dbopl.cpp                    \
		      Machine/Dbopl/hiopl.cpp                    \
		      Machine/Dbopl/DboplMachine.cpp             \
		      Machine/PBSynth/PBSynthUserInterface.cpp \
		      Machine/PBSynth/synthengine.cpp            \
		      Machine/PBSynth/osc.cpp                    \
		      Machine/PBSynth/lfo.cpp                    \
		      Machine/PBSynth/filter.cpp                 \
		      Machine/PBSynth/env.cpp                    \
		      Machine/PBSynth/echo.cpp                   \
		      Machine/PBSynth/osctab.cpp                 \
		      Machine/PBSynth/lfotab.cpp                 \
		      Machine/PBSynth/envtab.cpp                 \
		      Machine/PBSynth/coeff.cpp                  \
		      Machine/PBSynth/PBSynthMachine.cpp         \
		      Machine/Cursynth/CursynthUserInterface.cpp \
		      Machine/Cursynth/processor_router.cpp	 \
		      Machine/Cursynth/processor.cpp		 \
		      Machine/Cursynth/oscillator.cpp		 \
		      Machine/Cursynth/operators.cpp		 \
		      Machine/Cursynth/mono_panner.cpp		 \
		      Machine/Cursynth/midi_lookup.cpp		 \
		      Machine/Cursynth/linear_slope.cpp		 \
		      Machine/Cursynth/filter.cpp		 \
		      Machine/Cursynth/feedback.cpp		 \
		      Machine/Cursynth/envelope.cpp		 \
		      Machine/Cursynth/delay.cpp		 \
		      Machine/Cursynth/cursynth_strings.cpp	 \
		      Machine/Cursynth/cursynth_engine.cpp	 \
		      Machine/Cursynth/wave.cpp			 \
		      Machine/Cursynth/voice_handler.cpp	 \
		      Machine/Cursynth/value.cpp		 \
		      Machine/Cursynth/trigger_operators.cpp	 \
		      Machine/Cursynth/step_generator.cpp	 \
		      Machine/Cursynth/smooth_value.cpp		 \
		      Machine/Cursynth/smooth_filter.cpp	 \
		      Machine/Cursynth/send_receive.cpp		 \
		      Machine/Cursynth/CursynthMachine.cpp	 \
		      Machine/Open303/Open303Machine.cpp	 \
		      Machine/Open303/rosic_Open303.cpp		 \
		      Machine/Open303/Open303UserInterface.cpp	 \
		      Machine/Open303/rosic_MidiNoteEvent.cpp	 \
		      Machine/Open303/rosic_AcidSequencer.cpp	 \
		      Machine/Open303/rosic_Complex.cpp		 \
		      Machine/Open303/rosic_AcidPattern.cpp	 \
		      Machine/Open303/rosic_BlendOscillator.cpp	 \
		      Machine/Open303/rosic_OnePoleFilter.cpp	 \
		      Machine/Open303/rosic_NumberManipulations.cpp	\
		      Machine/Open303/rosic_FourierTransformerRadix2.cpp\
		      Machine/Open303/rosic_DecayEnvelope.cpp	\
		      Machine/Open303/rosic_MipMappedWaveTable.cpp	\
		      Machine/Open303/rosic_BiquadFilter.cpp		\
		      Machine/Open303/GlobalFunctions.cpp		\
		      Machine/Open303/rosic_AnalogEnvelope.cpp		\
		      Machine/Open303/rosic_TeeBeeFilter.cpp		\
		      Machine/Open303/rosic_LeakyIntegrator.cpp		\
		      Machine/Open303/rosic_FunctionTemplates.cpp	\
		      Machine/Open303/rosic_EllipticQuarterBandFilter.cpp\
		      Machine/Open303/rosic_RealFunctions.cpp		\
		      Machine/Twytch/TwytchsynthMachine.cpp		\
		      Machine/Twytch/TwytchsynthUserInterface.cpp	\
		      Machine/Twytch/twytch_alias.cpp				\
		      Machine/Twytch/twytch_arpeggiator.cpp			\
		      Machine/Twytch/twytch_bypass_router.cpp			\
		      Machine/Twytch/twytch_bit_crush.cpp			\
		      Machine/Twytch/twytch_fixed_point_oscillator.cpp		\
		      Machine/Twytch/twytch_filter.cpp				\
		      Machine/Twytch/twytch_feedback.cpp			\
		      Machine/Twytch/twytch_envelope.cpp			\
		      Machine/Twytch/twytch_distortion.cpp			\
		      Machine/Twytch/twytch_delay.cpp				\
		      Machine/Twytch/twytch_helm_lfo.cpp			\
		      Machine/Twytch/twytch_helm_engine.cpp			\
		      Machine/Twytch/twytch_helm_common.cpp			\
		      Machine/Twytch/twytch_formant_manager.cpp		\
		      Machine/Twytch/twytch_fixed_point_wave.cpp		\
		      Machine/Twytch/twytch_helm_voice_handler.cpp		\
		      Machine/Twytch/twytch_helm_oscillators.cpp		\
		      Machine/Twytch/twytch_helm_module.cpp			\
		      Machine/Twytch/twytch_operators.cpp			\
		      Machine/Twytch/twytch_noise_oscillator.cpp		\
		      Machine/Twytch/twytch_mono_panner.cpp			\
		      Machine/Twytch/twytch_midi_lookup.cpp			\
		      Machine/Twytch/twytch_memory.cpp				\
		      Machine/Twytch/twytch_magnitude_lookup.cpp		\
		      Machine/Twytch/twytch_linear_slope.cpp			\
		      Machine/Twytch/twytch_processor_router.cpp		\
		      Machine/Twytch/twytch_processor.cpp			\
		      Machine/Twytch/twytch_phaser.cpp				\
		      Machine/Twytch/twytch_oscillator.cpp			\
		      Machine/Twytch/twytch_reverb_comb.cpp			\
		      Machine/Twytch/twytch_reverb_all_pass.cpp		\
		      Machine/Twytch/twytch_reverb.cpp				\
		      Machine/Twytch/twytch_resonance_lookup.cpp		\
		      Machine/Twytch/twytch_resonance_cancel.cpp		\
		      Machine/Twytch/twytch_value.cpp				\
		      Machine/Twytch/twytch_trigger_operators.cpp		\
		      Machine/Twytch/twytch_switch.cpp				\
		      Machine/Twytch/twytch_stutter.cpp			\
		      Machine/Twytch/twytch_step_generator.cpp			\
		      Machine/Twytch/twytch_smooth_value.cpp			\
		      Machine/Twytch/twytch_smooth_filter.cpp			\
		      Machine/Twytch/twytch_simple_delay.cpp			\
		      Machine/Twytch/twytch_wave.cpp				\
		      Machine/Twytch/twytch_voice_handler.cpp			\
		      Machine/Twytch/twytch_detune_lookup.cpp			\
		      Machine/Twytch/twytch_sample_decay_lookup.cpp		\
		      Machine/Twytch/twytch_portamento_slope.cpp		\
		      Machine/Twytch/twytch_dc_filter.cpp			\
		      Machine/MidiOutSystem/MidiOutUserInterface.cpp            \
		      Machine/MidiOutSystem/MidiOutMachine.cpp                  \
		      Machine/MDADrum/MDADrumMachine.cpp			\
		      Machine/MDADrum/MDADrumUserInterface.cpp			\
		      Machine/MDADrum/drumsynth_oop5.cpp			\
		      Machine/MDADrum/profport.cpp				\
		      Machine/SIDSynth/sid.cpp					\
		      Machine/SIDSynth/wave.cpp					\
		      Machine/SIDSynth/sidfilter.cpp				\
		      Machine/SIDSynth/envelope.cpp				\
		      Machine/SIDSynth/extfilt.cpp				\
		      Machine/SIDSynth/pot.cpp					\
		      Machine/SIDSynth/voice.cpp				\
		      Machine/SIDSynth/wave8580__ST.cpp				\
		      Machine/SIDSynth/wave8580_P_T.cpp				\
		      Machine/SIDSynth/wave8580_PS_.cpp				\
		      Machine/SIDSynth/wave8580_PST.cpp				\
		      Machine/SIDSynth/wave6581__ST.cpp				\
		      Machine/SIDSynth/wave6581_P_T.cpp				\
		      Machine/SIDSynth/wave6581_PS_.cpp				\
		      Machine/SIDSynth/wave6581_PST.cpp				\
		      Machine/SIDSynth/SIDSynthMachine.cpp			\
		      Machine/SIDSynth/SIDSynthUserInterface.cpp





OBJDIR             =     debianrtaudio_sdl20
OBJECTS            =   $(SOURCES:.cpp=.o)
DEPENDENCY         =   $(SOURCES:.cpp=.d)

DEPENDENCYINOBJDIR = $(addprefix $(OBJDIR)/,$(DEPENDENCY))
OBJECTSINOBJDIR    = $(addprefix $(OBJDIR)/,$(OBJECTS))
OBJTOLINKINOBJDIR  = $(addprefix $(OBJDIR)/,$(OBJTOLINK))

EXECUTABLE=PatternPlayer_debian_Rtaudio_sdl20

#all: DIRTOCREATE $(DEPENDENCY) $(SOURCES) $(EXECUTABLE)

all: DIRTOCREATE $(DEPENDENCYINOBJDIR) $(SOURCES) $(EXECUTABLE) 

DIRTOCREATE:
	-mkdir -p $(OBJDIR)/Machine
	-mkdir -p $(OBJDIR)/Machine/Picosynth
	-mkdir -p $(OBJDIR)/Machine/Picodrum
	-mkdir -p $(OBJDIR)/Machine/Dbopl	
	-mkdir -p $(OBJDIR)/Machine/PBSynth
	-mkdir -p $(OBJDIR)/Machine/Cursynth
	-mkdir -p $(OBJDIR)/Machine/Open303
	-mkdir -p $(OBJDIR)/Machine/Twytch
	-mkdir -p $(OBJDIR)/Machine/MidiOutSystem
	-mkdir -p $(OBJDIR)/Machine/MDADrum
	-mkdir -p $(OBJDIR)/Machine/SIDSynth

$(EXECUTABLE): $(DEPENDENCYINOBJDIR) $(OBJECTSINOBJDIR)
	$(CC) $(OBJTOLINKINOBJDIR)  $(OBJECTSINOBJDIR) -o $@ $(LDFLAGS)

# the .d file contain the dependency
$(OBJDIR)/%.d : %.cpp %.h
	$(CC) $(CFLAGS_SDLVERS) -I. -MM $< -o $@

$(OBJDIR)/%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
-include $(DEPENDENCYINOBJDIR)


# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
$(OBJDIR)/SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) $(CFLAGS_SDLVERS) -I. -MM $< -o $@ 

# PatternPlayer.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) $(CFLAGS_SDLVERS) -std=c++11 -I. -MM $< -o $@ 


clean:
	-rm -f $(OBJECTSINOBJDIR)
	-rm -f $(DEPENDENCYINOBJDIR)
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)



