#CC=g++-4.4
CC=g++
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb 
CFLAGS= -c -O3 -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive -pg
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive -pg -DDUMP_AUDIO=0
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive 
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1 -DFIXED
CFLAGS= -c -O3 -D__LINUX__ -DLINUX -I. -LSDL/lib -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb   -DDUMP_AUDIO=1 -DFIXED

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL           -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread


OBJTOLINK=RtAudio.o

SOURCES=Machine.cpp Track.cpp AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp OneOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp Biquad.cpp PatternSequencer.cpp AudioDriverRTAudio.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp Effect.cpp EffectDelay.cpp SongSequencer.cpp WaveTableManager.cpp WaveTable.cpp Generator.cpp 


#Machine.cpp Track.cpp AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp OneOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp Biquad.cpp PatternSequencer.cpp AudioDriverRTAudio.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp Effect.cpp EffectDelay.cpp SongSequencer.cpp WaveTableManager.cpp WaveTable.cpp Generator.cpp 

SOURCES=PatternPlayer.cpp \
		      SDL_GUI.cpp              \
		      SYSTEMLINUX.cpp	       \
		      AudioEngine.cpp          \
		      AudioDriverRTAudio.cpp   \
		      Instrument.cpp           \
		      Synth.cpp                \
		      Oscillator.cpp           \
		      OneOscillator.cpp        \
		      Biquad.cpp               \
		      AudioMixer.cpp           \
		      Wave.cpp Track.cpp       \
		      Machine.cpp              \
		      MonoMixer.cpp            \
		      InputManager.cpp         \
		      Filter.cpp               \
		      AMSynthLowPassFilter.cpp \
		      Effect.cpp               \
		      EffectDelay.cpp          \
		      EffectDisabled.cpp       \
		      WaveTableManager.cpp     \
		      WaveTable.cpp            \
		      Generator.cpp            \
		      PatternElement.cpp       \
		      Pattern.cpp              \
		      PatternReader.cpp        \
		      Sequencer.cpp            \
		      PatternSequencer.cpp     \
		      SongSequencer.cpp        \
		      NoteFreq.cpp             \
		      PitchBend.cpp            \
		      TweakableKnob.cpp	       \
		      UserInterface.cpp	       \
		      Machine/Picosynth/PicosynthADSR.cpp        \
		      Machine/Picosynth/PicosynthVCO.cpp         \
		      Machine/Picosynth/PicosynthMachine.cpp     \
		      Machine/Picodrum/PicodrumVCO.cpp           \
		      Machine/Picodrum/PicodrumADSR.cpp          \
		      Machine/Picodrum/PicodrumMachine.cpp       \
		      Machine/Dbopl/dbopl.cpp                    \
		      Machine/Dbopl/hiopl.cpp                    \
		      Machine/Dbopl/DboplMachine.cpp             \
		      Machine/PBSynth/synthengine.cpp            \
		      Machine/PBSynth/osc.cpp                    \
		      Machine/PBSynth/lfo.cpp                    \
		      Machine/PBSynth/filter.cpp                 \
		      Machine/PBSynth/env.cpp                    \
		      Machine/PBSynth/echo.cpp                   \
		      Machine/PBSynth/osctab.cpp                 \
		      Machine/PBSynth/lfotab.cpp                 \
		      Machine/PBSynth/envtab.cpp                 \
		      Machine/PBSynth/coeff.cpp                  \
		      Machine/PBSynth/PBSynthMachine.cpp         \





OBJECTS=$(SOURCES:.cpp=.o)
DEPENDENCY=$(SOURCES:.cpp=.d)
EXECUTABLE=PatternPlayer_debian_Rtaudio

all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)


%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
include ${DEPENDENCY}

# the .d file contain the dependency
%.d : %.cpp %.h
	$(CC) -I. -MM $< -o $@

# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) -I. -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) -I. -MM $< -o $@ 


clean:
	-rm -f $(OBJECTS) 
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)