include Makefile_sources
CC=g++
CC=/opt/opendingux-toolchain/usr/bin/mipsel-linux-g++

CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o   

CFLAGS=-c -DLINUX -I. -LSDL/lib
CFLAGS=-c -O3 -DLINUX -D__RTAUDIO__ -DOPENDINGUX -I. -I/opt/opendingux-toolchain/usr/include/ -L/opt/opendingux-toolchain/usr/lib/ -lSDL -lSDL_ttf -fpermissive -DFIXED -fno-rtti -fomit-frame-pointer -ffunction-sections -ffast-math -fsingle-precision-constant -G0

CFLAGS_SDLVERS=-D__SDL12__
CFLAGS=-c -O3 ${CFLAGS_SDLVERS} -DLINUX -D__RTAUDIO__ -D__LINUX_ALSA__ -DOPENDINGUX -I. -I/opt/opendingux-toolchain/usr/include/ -L/opt/opendingux-toolchain/usr/lib/ -lSDL -lSDL_ttf -fpermissive -DFIXED -fno-rtti -fomit-frame-pointer -ffunction-sections -ffast-math -fsingle-precision-constant -G0  
#-DDEBUGPRINTF

LDFLAGS=-L/opt/opendingux-toolchain/usr/lib/ -lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread  -DFIXED

OBJTOLINK=RtAudio.o
OBJTOLINK=

SOURCES=$(SOURCES_PICOLOOP)	\
		RtAudio.cpp		\
		AudioDriverRTAudio.cpp   \
		SYSTEMLINUX.cpp	       \
		$(SOURCES_PICOSYNTH) 	\
		$(SOURCES_PICODRUM) 	\
		$(SOURCES_DBOPL) 	\
		$(SOURCES_PBSYNTH)


OBJDIR             =     opendinguxrtaudio
OBJECTS            =   $(SOURCES:.cpp=.o)
DEPENDENCY         =   $(SOURCES:.cpp=.d)

DEPENDENCYINOBJDIR = $(addprefix $(OBJDIR)/,$(DEPENDENCY))
OBJECTSINOBJDIR    = $(addprefix $(OBJDIR)/,$(OBJECTS))
OBJTOLINKINOBJDIR  = $(addprefix $(OBJDIR)/,$(OBJTOLINK))


EXECUTABLE=PatternPlayer.dge

all: DIRTOCREATE $(DEPENDENCYINOBJDIR) $(SOURCES) $(EXECUTABLE) 

DIRTOCREATE:
	-mkdir -p $(OBJDIR)/Machine
	-mkdir -p $(OBJDIR)/Machine/Picosynth
	-mkdir -p $(OBJDIR)/Machine/Picodrum
	-mkdir -p $(OBJDIR)/Machine/Dbopl	
	-mkdir -p $(OBJDIR)/Machine/PBSynth


$(EXECUTABLE): $(DEPENDENCYINOBJDIR) $(OBJECTSINOBJDIR)
	$(CC) $(OBJTOLINKINOBJDIR)  $(OBJECTSINOBJDIR) -o $@ $(LDFLAGS)

# the .d file contain the dependency
$(OBJDIR)/%.d : %.cpp %.h
	$(CC) ${CFLAGS_SDLVERS} -I. -MM $< -o $@

$(OBJDIR)/%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@

# include all the dependency .d file into the makefile 
# it allow to match change in .h file
-include $(DEPENDENCYINOBJDIR)

# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
$(OBJDIR)/SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) ${CFLAGS_SDLVERS} -I. -MM $< -o $@ 


# PatternPlayer.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) ${CFLAGS_SDLVERS} -std=c++11 -I. -MM $< -o $@ 


clean:
	-rm -f $(OBJECTSINOBJDIR)
	-rm -f $(DEPENDENCYINOBJDIR)
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
