CC=g++
CC=i586-mingw32msvc-g++
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
CFLAGS= -c -O3 -D__WIN32__ -I/c/MinGW/include/  -DLINUX -I. -ISDL_windows -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb 

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
#LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
LDFLAGS=-L. -lSDL -lSDL_ttf 
LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
LDFLAGS=-D__WIN32__ -L. -LSDL-1.2.15/lib/ -lmingw32 -lSDLmain -lSDL -lSDL_ttf -static-libgcc -ggdb
LDFLAGS=-D__WIN32__ -L. -LSDL_windows/lib -L/home/yoyz/.wine/drive_c/users/yoyz/Temp/DXF/DXSDK/lib/ -lmingw32 -lSDLmain -static-libgcc  -static-libstdc++ -lSDL -lSDL_ttf -ldsound -lole32 -lwinmm  -ggdb
LDFLAGS=-D__WIN32__ -L. -LSDL_windows/lib -L/home/yoyz/.wine/drive_c/users/yoyz/Temp/DXF/DXSDK/lib/ -lmingw32 -lSDLmain -static-libgcc  -lSDL -lSDL_ttf -ldsound -lole32 -lwinmm  -ggdb

OBJTOLINK=RtAudio.o
SOURCES=PatternPlayer.cpp			\
			SDL_GUI.cpp		\
			SYSTEMWINDOWS.cpp	\
			AudioEngine.cpp		\
			AudioDriverRTAudio.cpp	\
			Instrument.cpp		\
			Synth.cpp		\
			Oscillator.cpp		\
			OneOscillator.cpp	\
			Biquad.cpp		\
			AudioMixer.cpp		\
			Wave.cpp Track.cpp	\
			Machine.cpp		\
			MonoMixer.cpp		\
			InputManager.cpp	\
			Filter.cpp		\
			AMSynthLowPassFilter.cpp\
			Effect.cpp		\
			EffectDelay.cpp		\
			WaveTableManager.cpp	\
			WaveTable.cpp		\
			Generator.cpp		\
			PatternElement.cpp	\
			Pattern.cpp		\
			PatternReader.cpp	\
			Sequencer.cpp		\
			PatternSequencer.cpp	\
			SongSequencer.cpp	\
			NoteFreq.cpp            \
			PitchBend.cpp           \
			Machine/Picosynth/PicosynthADSR.cpp		\
			Machine/Picosynth/PicosynthVCO.cpp		\
			Machine/Picosynth/PicosynthMachine.cpp		\
			Machine/Picodrum/PicodrumVCO.cpp		\
			Machine/Picodrum/PicodrumADSR.cpp		\
			Machine/Picodrum/PicodrumMachine.cpp		\
			Machine/Dbopl/dbopl.cpp				\
			Machine/Dbopl/hiopl.cpp				\
			Machine/Dbopl/DboplMachine.cpp			\


OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=PatternPlayer_Rtaudio.exe

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
