include Makefile_sources
CC=g++
CC=i586-mingw32msvc-g++
CC=i686-w64-mingw32-g++-win32
CC=x86_64-w64-mingw32-g++
CC=i686-w64-mingw32-g++-win32
CC=i686-w64-mingw32-g++
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
CFLAGS= -O3 -D__WIN32__ -I/c/MinGW/include/  -DLINUX -I. -ISDL_windows -D__RTAUDIO__ -DLINUX_DESKTOP -ggdb 
CFLAGS= -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/ -I/usr/i686-w64-mingw32/include/ -DLINUX -I. -ISDL_windows -D__RTAUDIO__ -D__RTMIDI__ -DLINUX_DESKTOP -ggdb -fpermissive
CFLAGS= -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/ -I/usr/i686-w64-mingw32/include/ -I. -ISDL_windows -D__RTAUDIO__ -D__RTMIDI__ -DPC_DESKTOP -ggdb -fpermissive
CFLAGS= -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/ -I/usr/i686-w64-mingw32/include/ -I. -ISDL_windows -D__RTAUDIO__ -D__RTMIDI__ -DPC_DESKTOP -ggdb -fpermissive

CFLAGS_SDLVERS=-D__SDL12__
CFLAGS= -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/ -I/usr/i686-w64-mingw32/include/ -I. -ISDL_windows ${CFLAGS_SDLVERS} -D__RTAUDIO__ -D__RTMIDI__ -DPC_DESKTOP -ggdb -fpermissive

CFLAGS= -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/ -I/usr/i686-w64-mingw32/include/ -I. -ISDL_windows ${CFLAGS_SDLVERS} -D__RTAUDIO__ -D__RTMIDI__ -DPC_DESKTOP -ggdb -fpermissive 

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
#LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
LDFLAGS=-L. -lSDL -lSDL_ttf 
LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
LDFLAGS=-D__WIN32__ -L. -LSDL-1.2.15/lib/ -lmingw32 -lSDLmain -lSDL -lSDL_ttf -static-libgcc -ggdb
LDFLAGS=-D__WIN32__ -L. -LSDL_windows/lib -L/home/yoyz/.wine/drive_c/users/yoyz/Temp/DXF/DXSDK/lib/ -lmingw32 -lSDLmain -static-libgcc  -static-libstdc++ -lSDL -lSDL_ttf -ldsound -lole32 -lwinmm  -ggdb

LDFLAGS=-D__WIN32__ -L. -LSDL_windows/lib -L/home/yoyz/.wine/drive_c/users/yoyz/Temp/DXF/DXSDK/lib/ -lmingw32 -lSDLmain -static-libgcc  -static-libstdc++ -lSDL -lSDL_ttf -ldsound -lole32 -lwinmm   -lkernel32 -ggdb 

OBJTOLINK=RtAudio.o RtMidi.o
SOURCES= \
			AudioDriverRTAudio.cpp	\
			SYSTEMWINDOWS.cpp	\
			SysMutex.cpp	       \
			MidiOutSystem.cpp	       \
		        MidiInSystem.cpp	       \
			$(SOURCES_PICOLOOP)     \
			$(SOURCES_PICOSYNTH) \
			$(SOURCES_PICODRUM) \
			$(SOURCES_DBOPL) \
			$(SOURCES_PBSYNTH) \
			$(SOURCES_CURSYNTH) \
			$(SOURCES_OPEN303) \
			$(SOURCES_TWYTCH) \
			$(SOURCES_MIDIOUT) \
			$(SOURCES_MDADRUM) \
			$(SOURCES_SIDSYNTH) \
			$(SOURCES_LGPTSAMPLERSYNTH) 








OBJDIR             =     windowsrtaudio
OBJECTS            =   $(SOURCES:.cpp=.o)
DEPENDENCY         =   $(SOURCES:.cpp=.d)

DEPENDENCYINOBJDIR = $(addprefix $(OBJDIR)/,$(DEPENDENCY))
OBJECTSINOBJDIR    = $(addprefix $(OBJDIR)/,$(OBJECTS))
OBJTOLINKINOBJDIR  = $(addprefix $(OBJDIR)/,$(OBJTOLINK))



#DEPENDENCY=$(SOURCES:.cpp=.d)

EXECUTABLE=PatternPlayer_windows_Rtaudio.exe

#all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE)
all:  $(DEPENDENCYINOBJDIR) $(SOURCES) $(EXECUTABLE)



$(EXECUTABLE): $(DEPENDENCYINOBJDIR) $(OBJECTSINOBJDIR)
	$(CC) $(OBJTOLINKINOBJDIR)  $(OBJECTSINOBJDIR) -o $@ $(LDFLAGS)

# the .d file contain the dependency
$(OBJDIR)/%.d : %.cpp %.h
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) ${CFLAGS_SDLVERS} -I. -ISDL_windows -MM $< -o $@

$(OBJDIR)/%.o : %.cpp
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) -c $(CFLAGS) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
-include ${DEPENDENCYINOBJDIR}


# SYSTEMWINDOWS.d does have a .h which is SYSTEM.h, so it need a tweaks
$(OBJDIR)/SYSTEMWINDOWS.d:SYSTEMWINDOWS.cpp
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) ${CFLAGS_SDLVERS} -I. -ISDL_windows -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
$(OBJDIR)/PatternPlayer.d:PatternPlayer.cpp
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) ${CFLAGS_SDLVERS} -I. -ISDL_windows -MM $< -o $@ 



clean:
	-rm -f $(OBJECTSINOBJDIR)
	-rm -f $(DEPENDENCYINOBJDIR)
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
