CC=g++
CC=/opt/open2x/gcc-4.1.1-glibc-2.3.6/bin/arm-open2x-linux-g++

#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-c -O3 -DLINUX -I. -DGP2X -D__SDL_AUDIO__ -I/opt/open2x/include/SDL/ -I/opt/open2x/include/ -L/opt/open2x/lib/ -g -fpermissive

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread 
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -L/opt/open2x/lib/ -lfreetype -lz


#OBJTOLINK=RtAudio.o

#SOURCES=Wave.cpp Synth.cpp Instrument.cpp Machine.cpp Track.cpp AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp SineOscillator.cpp SawOscillator.cpp  FuzzyPulseOscillator.cpp PulseOscillator.cpp  TriangleOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp WaveTableSineOscillator.cpp NoiseOscillator.cpp OneOscillator.cpp Biquad.cpp PatternSequencer.cpp AudioDriverSDL.cpp
SOURCES=PatternPlayer.cpp  SYSTEMLINUX.cpp Machine.cpp PatternSequencer.cpp Effect.cpp WaveTable.cpp AudioDriverSDL.cpp EffectDelay.cpp AMSynthLowPassFilter.cpp InputManager.cpp Generator.cpp PitchBend.cpp NoteFreq.cpp WaveTableManager.cpp Sequencer.cpp Oscillator.cpp OneOscillator.cpp SongSequencer.cpp Filter.cpp Synth.cpp Biquad.cpp Track.cpp Pattern.cpp MonoMixer.cpp SDL_GUI.cpp AudioEngine.cpp PatternElement.cpp AudioMixer.cpp Instrument.cpp PatternReader.cpp Wave.cpp Machine/Picodrum/PicodrumADSR.cpp  Machine/Picodrum/PicodrumMachine.cpp  Machine/Picodrum/PicodrumVCO.cpp Machine/Picosynth/PicosynthADSR.cpp  Machine/Picosynth/PicosynthMachine.cpp  Machine/Picosynth/PicosynthVCO.cpp Machine/Dbopl/DboplMachine.cpp  Machine/Dbopl/dbopl.cpp  Machine/Dbopl/hiopl.cpp

OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=PatternPlayer

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
