CC=g++
CFLAGS=-c -DLINUX -I. -LSDL/lib -g
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf
SOURCES=WaveView.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=WaveView

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS) 

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
