CC=g++
CC=/opt/open2x/gcc-4.1.1-glibc-2.3.6/bin/arm-open2x-linux-g++

#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-c -O3 -DLINUX -I. -DGP2X -D__SDL_AUDIO__ -I/opt/open2x/include/SDL/ -I/opt/open2x/include/ -L/opt/open2x/lib/ -g -fpermissive
CFLAGS=-c -O3 -DLINUX -I. -DGP2X -D__SDL_AUDIO__ -I/opt/open2x/include/SDL/ -I/opt/open2x/include/ -L/opt/open2x/lib/ -g -fpermissive -pg
CFLAGS=-c -O3 -DLINUX -I. -DGP2X -D__SDL_AUDIO__ -DFIXED -I/opt/open2x/include/SDL/ -I/opt/open2x/include/ -L/opt/open2x/lib/ -g -fpermissive -ffast-math

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread 
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -L/opt/open2x/lib/ -lfreetype -lz
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -L/opt/open2x/lib/ -lfreetype -lz -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -L/opt/open2x/lib/ -lfreetype -lz

#OBJTOLINK=RtAudio.o

#SOURCES=Wave.cpp Synth.cpp Instrument.cpp Machine.cpp  AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp SineOscillator.cpp SawOscillator.cpp  FuzzyPulseOscillator.cpp PulseOscillator.cpp  TriangleOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp WaveTableSineOscillator.cpp NoiseOscillator.cpp OneOscillator.cpp Biquad.cpp PatternSequencer.cpp AudioDriverSDL.cpp

#SOURCES=PatternPlayer.cpp  SYSTEMLINUX.cpp Machine.cpp PatternSequencer.cpp Effect.cpp WaveTable.cpp AudioDriverSDL.cpp EffectDelay.cpp AMSynthLowPassFilter.cpp InputManager.cpp Generator.cpp PitchBend.cpp 		      TweakableKnob.cpp	       NoteFreq.cpp WaveTableManager.cpp Sequencer.cpp Oscillator.cpp OneOscillator.cpp SongSequencer.cpp Filter.cpp Synth.cpp Biquad.cpp  Pattern.cpp MonoMixer.cpp SDL_GUI.cpp AudioEngine.cpp PatternElement.cpp AudioMixer.cpp Instrument.cpp PatternReader.cpp Wave.cpp Machine/Picodrum/PicodrumADSR.cpp  Machine/Picodrum/PicodrumMachine.cpp  Machine/Picodrum/PicodrumVCO.cpp Machine/Picosynth/PicosynthADSR.cpp  Machine/Picosynth/PicosynthMachine.cpp  Machine/Picosynth/PicosynthVCO.cpp Machine/Dbopl/DboplMachine.cpp  Machine/Dbopl/dbopl.cpp  Machine/Dbopl/hiopl.cpp

SOURCES=PatternPlayer.cpp \
		      SDL_GUI.cpp              \
		      SYSTEMLINUX.cpp	       \
		      AudioEngine.cpp          \
		      AudioDriverSDL.cpp       \
		      Instrument.cpp           \
		      Synth.cpp                \
		      Oscillator.cpp           \
		      OneOscillator.cpp        \
		      Biquad.cpp               \
		      AudioMixer.cpp           \
		      Wave.cpp        \
		      Machine.cpp              \
		      MonoMixer.cpp            \
		      InputManager.cpp         \
		      Filter.cpp               \
		      AMSynthLowPassFilter.cpp \
		      Effect.cpp               \
		      EffectDelay.cpp          \
		      EffectDisabled.cpp       \
		      WaveTableManager.cpp     \
		      WaveTable.cpp            \
		      Generator.cpp            \
		      PatternElement.cpp       \
		      Pattern.cpp              \
		      PatternReader.cpp        \
		      Sequencer.cpp            \
		      PatternSequencer.cpp     \
		      SongSequencer.cpp        \
		      NoteFreq.cpp             \
		      PitchBend.cpp            \
		      TweakableKnob.cpp	       \
		      UserInterface.cpp	       \
		      Machine/Picosynth/PicosynthUserInterface.cpp \
		      Machine/Picosynth/PicosynthADSR.cpp        \
		      Machine/Picosynth/PicosynthVCO.cpp         \
		      Machine/Picosynth/PicosynthMachine.cpp     \
		      Machine/Picodrum/PicodrumUserInterface.cpp \
		      Machine/Picodrum/PicodrumVCO.cpp           \
		      Machine/Picodrum/PicodrumADSR.cpp          \
		      Machine/Picodrum/PicodrumMachine.cpp       \
		      Machine/Dbopl/DboplUserInterface.cpp       \
		      Machine/Dbopl/dbopl.cpp                    \
		      Machine/Dbopl/hiopl.cpp                    \
		      Machine/Dbopl/DboplMachine.cpp             \
		      Machine/PBSynth/PBSynthUserInterface.cpp   \
		      Machine/PBSynth/synthengine.cpp            \
		      Machine/PBSynth/osc.cpp                    \
		      Machine/PBSynth/lfo.cpp                    \
		      Machine/PBSynth/filter.cpp                 \
		      Machine/PBSynth/env.cpp                    \
		      Machine/PBSynth/echo.cpp                   \
		      Machine/PBSynth/osctab.cpp                 \
		      Machine/PBSynth/lfotab.cpp                 \
		      Machine/PBSynth/envtab.cpp                 \
		      Machine/PBSynth/coeff.cpp                  \
		      Machine/PBSynth/PBSynthMachine.cpp         \




OBJECTS=$(SOURCES:.cpp=.o)
DEPENDENCY=$(SOURCES:.cpp=.d)
EXECUTABLE=PatternPlayer.gpe

all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)


%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
include ${DEPENDENCY}

# the .d file contain the dependency
%.d : %.cpp %.h
	$(CC) -I. -I/opt/open2x/include -MM $< -o $@

# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) -I. -I/opt/open2x/include -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) -I. -I/opt/open2x/include -MM $< -o $@ 


clean:
	-rm -f $(OBJECTS) 
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)

#
#OBJECTS=$(SOURCES:.cpp=.o)
#EXECUTABLE=PatternPlayer.gpe
#
#all: $(SOURCES) $(EXECUTABLE)
#
#$(EXECUTABLE): $(OBJECTS)
#	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@
#
#.cpp.o:
#	$(CC) $(CFLAGS) $< -o $@
#
#clean:
#	-rm -f $(OBJECTS) $(EXECUTABLE)
