include Makefile_sources

CC=clang++
CC=g++
CFLAGS_SDLVERS=-D__SDL20__    

SYNTH=
SYNTH+= -DENABLE_SYNTH_PICOSYNTH
SYNTH+= -DENABLE_SYNTH_PICODRUM
SYNTH+= -DENABLE_SYNTH_OPL2
SYNTH+=  -DENABLE_SYNTH_PBSYNTH
#SYNTH+= -DENABLE_SYNTH_LGPTSAMPLER
#SYNTH+= -DENABLE_SYNTH_CURSYNTH
#SYNTH+= -DENABLE_SYNTH_OPEN303
#SYNTH+= -DENABLE_SYNTH_TWYTCHSYNTH
#SYNTH+= -DENABLE_SYNTH_MDADRUM
#SYNTH+= -DENABLE_SYNTH_SIDSYNTH
#SYNTH+= -DENABLE_SYNTH_MIDIOUT


CFLAGS_HELPER=-I/home/yoyz/local/SDL2-clang/include/
LDFLAGS_HELPER=-L/home/yoyz/local/SDL2-clang/lib
CFLAGS_HELPER=
LDFLAGS_HELPER=


CFLAGS= -c -std=c++11 -O1 -D__LINUX__ -DLINUX -D__LINUX_PULSE__ -I. ${CFLAGS_HELPER} ${LDFLAGS_HELPER}  -D__SDL20__  -D__SDL_AUDIO__ -DPC_DESKTOP   -ggdb  ${CFLAGS_SDLVERS}                 -DDEBUGPRINTF=1 -DSCREEN_MULT=2  -DNDEBUG -Werror=return-type ${SYNTH} -D__PBSYNTHONLY__ -DBUFFER_FRAME=512


LDFLAGS=${LDFLAGS_HELPER} -lSDL2 -lSDL2_ttf -lpthread -lpulse -lpulse-simple 



OBJTOLINK=
SOURCES=WaveSynth.cpp                      \
			AudioDriverSDL.cpp \
			SYSTEMLINUX.cpp    \
			$(SOURCES_PICODEP) \
			$(SOURCES_PICOSYNTH)  \
			$(SOURCES_PICODRUM)  \
			$(SOURCES_DBOPL)  \
			$(SOURCES_PBSYNTH)  \
		      


OBJDIR             =   wavesynth_sdl20
OBJECTS            =   $(SOURCES:.cpp=.o)
DEPENDENCY         =   $(SOURCES:.cpp=.d)

DEPENDENCYINOBJDIR = $(addprefix $(OBJDIR)/,$(DEPENDENCY))
OBJECTSINOBJDIR    = $(addprefix $(OBJDIR)/,$(OBJECTS))
OBJTOLINKINOBJDIR  = $(addprefix $(OBJDIR)/,$(OBJTOLINK))

EXECUTABLE=pbsynthsdl_${OBJDIR}

all: DIRTOCREATE $(DEPENDENCYINOBJDIR) $(SOURCES) $(EXECUTABLE) 

DIRTOCREATE:
	-mkdir -p $(OBJDIR)/Machine
	-mkdir -p $(OBJDIR)/Machine/Picosynth
	-mkdir -p $(OBJDIR)/Machine/Picodrum
	-mkdir -p $(OBJDIR)/Machine/Dbopl	
	-mkdir -p $(OBJDIR)/Machine/PBSynth
	-mkdir -p $(OBJDIR)/Machine/Cursynth
	-mkdir -p $(OBJDIR)/Machine/Open303
	-mkdir -p $(OBJDIR)/Machine/Twytch
	-mkdir -p $(OBJDIR)/Machine/MidiOutSystem
	-mkdir -p $(OBJDIR)/Machine/MDADrum
	-mkdir -p $(OBJDIR)/Machine/SIDSynth
	-mkdir -p $(OBJDIR)/Machine/Lgptsampler

$(EXECUTABLE): $(DEPENDENCYINOBJDIR) $(OBJECTSINOBJDIR)
	$(CC) $(OBJTOLINKINOBJDIR)  $(OBJECTSINOBJDIR) -o $@ $(LDFLAGS)

# the .d file contain the dependency
$(OBJDIR)/%.d : %.cpp %.h
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) -std=c++11 $(CFLAGS_SDLVERS) $(CFLAGS_HELPER) -I. -MM $< -o $@

$(OBJDIR)/%.o : %.cpp 
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) $(CFLAGS) $(CFLAGS_HELPER) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
-include $(DEPENDENCYINOBJDIR)


# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
$(OBJDIR)/SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC) -std=c++11 -I. -MM $< -o $@ 

# PatternPlayer.d does have a .h which is system.h
$(OBJDIR)/WaveSynth.d:WaveSynth.cpp
	@[ -d `dirname $@` ] || mkdir -p `dirname $@`
	$(CC)  $(CFLAGS_SDLVERS) $(CFLAGS_HELPER)  -std=c++11 -I. -MM $< -o $@ 


clean:
	-rm -f $(OBJECTSINOBJDIR)
	-rm -f $(DEPENDENCYINOBJDIR)
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
