CC=g++
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
CFLAGS= -c -O3 -DLINUX -I. -LSDL/lib -D__SDL_AUDIO__  -DLINUX_DESKTOP -ggdb  -fpermissive
CFLAGS= -c -O3 -DLINUX -I. -LSDL/lib -D__SDL_AUDIO__  -DLINUX_DESKTOP -ggdb  -fpermissive -DFIXED

LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL           -lSDL_ttf -lpthread -pg
LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread

SOURCES=PatternPlayer.cpp \
		      SDL_GUI.cpp              \
		      SYSTEMLINUX.cpp	       \
		      AudioEngine.cpp          \
		      AudioDriverSDL.cpp       \
		      Instrument.cpp           \
		      Synth.cpp                \
		      Oscillator.cpp           \
		      OneOscillator.cpp        \
		      Biquad.cpp               \
		      AudioMixer.cpp           \
		      Wave.cpp Track.cpp       \
		      Machine.cpp              \
		      MonoMixer.cpp            \
		      InputManager.cpp         \
		      Filter.cpp               \
		      AMSynthLowPassFilter.cpp \
		      Effect.cpp               \
		      EffectDelay.cpp          \
		      EffectDisabled.cpp       \
		      WaveTableManager.cpp     \
		      WaveTable.cpp            \
		      Generator.cpp            \
		      PatternElement.cpp       \
		      Pattern.cpp              \
		      PatternReader.cpp        \
		      Sequencer.cpp            \
		      PatternSequencer.cpp     \
		      SongSequencer.cpp        \
		      NoteFreq.cpp             \
		      PitchBend.cpp            \
		      TweakableKnob.cpp	       \
		      UserInterface.cpp	       \
		      Machine/Picosynth/PicosynthUserInterface.cpp \
		      Machine/Picosynth/PicosynthADSR.cpp        \
		      Machine/Picosynth/PicosynthVCO.cpp         \
		      Machine/Picosynth/PicosynthMachine.cpp     \
		      Machine/Picodrum/PicodrumUserInterface.cpp \
		      Machine/Picodrum/PicodrumVCO.cpp           \
		      Machine/Picodrum/PicodrumADSR.cpp          \
		      Machine/Picodrum/PicodrumMachine.cpp       \
		      Machine/Dbopl/DboplUserInterface.cpp \
		      Machine/Dbopl/dbopl.cpp                    \
		      Machine/Dbopl/hiopl.cpp                    \
		      Machine/Dbopl/DboplMachine.cpp             \
		      Machine/PBSynth/PBSynthUserInterface.cpp \
		      Machine/PBSynth/synthengine.cpp            \
		      Machine/PBSynth/osc.cpp                    \
		      Machine/PBSynth/lfo.cpp                    \
		      Machine/PBSynth/filter.cpp                 \
		      Machine/PBSynth/env.cpp                    \
		      Machine/PBSynth/echo.cpp                   \
		      Machine/PBSynth/osctab.cpp                 \
		      Machine/PBSynth/lfotab.cpp                 \
		      Machine/PBSynth/envtab.cpp                 \
		      Machine/PBSynth/coeff.cpp                  \
		      Machine/PBSynth/PBSynthMachine.cpp         \
		      Machine/Cursynth/CursynthUserInterface.cpp \
		      Machine/Cursynth/processor_router.cpp	 \
		      Machine/Cursynth/processor.cpp		 \
		      Machine/Cursynth/oscillator.cpp		 \
		      Machine/Cursynth/operators.cpp		 \
		      Machine/Cursynth/mono_panner.cpp		 \
		      Machine/Cursynth/midi_lookup.cpp		 \
		      Machine/Cursynth/linear_slope.cpp		 \
		      Machine/Cursynth/filter.cpp		 \
		      Machine/Cursynth/feedback.cpp		 \
		      Machine/Cursynth/envelope.cpp		 \
		      Machine/Cursynth/delay.cpp		 \
		      Machine/Cursynth/cursynth_strings.cpp	 \
		      Machine/Cursynth/cursynth_engine.cpp	 \
		      Machine/Cursynth/wave.cpp			 \
		      Machine/Cursynth/voice_handler.cpp	 \
		      Machine/Cursynth/value.cpp		 \
		      Machine/Cursynth/trigger_operators.cpp	 \
		      Machine/Cursynth/step_generator.cpp	 \
		      Machine/Cursynth/smooth_value.cpp		 \
		      Machine/Cursynth/smooth_filter.cpp	 \
		      Machine/Cursynth/send_receive.cpp		 \
		      Machine/Cursynth/CursynthMachine.cpp	 \





OBJECTS=$(SOURCES:.cpp=.o)
DEPENDENCY=$(SOURCES:.cpp=.d)
EXECUTABLE=PatternPlayer_debian_SDL

all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)


%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@


# include all the dependency .d file into the makefile 
# it allow to match change in .h file
include ${DEPENDENCY}

# the .d file contain the dependency
%.d : %.cpp %.h
	$(CC) -I. -MM $< -o $@

# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) -I. -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) -I. -MM $< -o $@ 


clean:
	-rm -f $(OBJECTS) 
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
