CC=g++
CFLAGS=-c -DLINUX -I. -LSDL/lib -g
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf
SOURCES=SineOscillator.cpp Wave.cpp Synth.cpp Instrument.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp WaveTest.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=WaveTest

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
