CC=g++
#CC=i586-mingw32msvc-g++
CC=i686-w64-mingw32-g++-win32
#CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  -pg
#LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o 

#CFLAGS=-c -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP

CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb -ffast-math
CFLAGS=-c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  -pg
CFLAGS=-Wall -c -O3 -DLINUX -I. -LSDL/lib -DLINUX_DESKTOP -ggdb  
#CFLAGS= -c -O1 -D__WIN32__ -I/c/MinGW/include/  -DLINUX -I. -LSDL/lib -D__SDL_AUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive
CFLAGS=  -c -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/  -DLINUX -I. -ISDL_windows -D__SDL_AUDIO__ -DLINUX_DESKTOP -ggdb  -fpermissive
CFLAGS=  -c -std=c++11 -O3 -DWIN32 -D__WIN32__ -I/c/MinGW/include/  -I. -ISDL_windows -D__SDL_AUDIO__ -DPC_DESKTOP -ggdb  -fpermissive


LDFLAGS=-lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread -pg
#LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
LDFLAGS=-L. -lSDL -lSDL_ttf 
LDFLAGS=-L. -lmingw32 -lSDLmain -lSDL -lSDL_ttf
#LDFLAGS=-D__WIN32__ -L. -LSDL-1.2.15/lib/ -lmingw32 -lSDLmain -lSDL -lSDL_ttf -static-libgcc -static-libstdc++ -ggdb
LDFLAGS=-D__WIN32__ -L. -LSDL_windows/lib -L/home/yoyz/.wine/drive_c/users/yoyz/Temp/DXF/DXSDK/lib/ -lmingw32 -lSDLmain -static-libgcc  -static-libstdc++  -lSDL -lSDL_ttf -ldsound -lole32 -lwinmm  -ggdb




SOURCES=PatternPlayer.cpp			\
			SDL_GUI.cpp		\
			SYSTEMWINDOWS.cpp	\
			AudioEngine.cpp		\
			AudioDriverSDL.cpp	\
			Instrument.cpp		\
			Synth.cpp		\
			Oscillator.cpp		\
			OneOscillator.cpp	\
			Biquad.cpp		\
			AudioMixer.cpp		\
			Wave.cpp 	\
			Machine.cpp		\
			MonoMixer.cpp		\
			InputManager.cpp	\
			Filter.cpp		\
			AMSynthLowPassFilter.cpp\
			Effect.cpp		\
			EffectDelay.cpp		\
			EffectDisabled.cpp      \
			WaveTableManager.cpp	\
			WaveTable.cpp		\
			Generator.cpp		\
			PatternElement.cpp	\
			Pattern.cpp		\
			PatternReader.cpp	\
			Sequencer.cpp		\
			PatternSequencer.cpp	\
			SongSequencer.cpp	\
			NoteFreq.cpp            \
			PitchBend.cpp           \
			TweakableKnob.cpp       \
			UserInterface.cpp	\
			Machine/Picosynth/PicosynthMachine.cpp		\
			Machine/Picosynth/PicosynthUserInterface.cpp	\
			Machine/Picosynth/PicosynthADSR.cpp		\
			Machine/Picosynth/PicosynthVCO.cpp		\
			Machine/Picodrum/PicodrumMachine.cpp		\
			Machine/Picodrum/PicodrumUserInterface.cpp 	\
			Machine/Picodrum/PicodrumVCO.cpp           	\
			Machine/Picodrum/PicodrumADSR.cpp          	\
			Machine/Dbopl/DboplMachine.cpp			\
			Machine/Dbopl/DboplUserInterface.cpp 		\
			Machine/Dbopl/dbopl.cpp				\
			Machine/Dbopl/hiopl.cpp				\
			Machine/PBSynth/PBSynthMachine.cpp         	\
			Machine/PBSynth/PBSynthUserInterface.cpp 	\
			Machine/PBSynth/synthengine.cpp            	\
			Machine/PBSynth/osc.cpp                    	\
			Machine/PBSynth/lfo.cpp                    	\
			Machine/PBSynth/filter.cpp                 	\
			Machine/PBSynth/env.cpp                    	\
			Machine/PBSynth/echo.cpp                   	\
			Machine/PBSynth/osctab.cpp                 	\
			Machine/PBSynth/lfotab.cpp                 	\
			Machine/PBSynth/envtab.cpp                 	\
			Machine/PBSynth/coeff.cpp                  	\
			Machine/Cursynth/CursynthMachine.cpp	 	\
			Machine/Cursynth/CursynthUserInterface.cpp 	\
			Machine/Cursynth/processor_router.cpp	   	\
			Machine/Cursynth/processor.cpp		   	\
			Machine/Cursynth/oscillator.cpp		 	\
			Machine/Cursynth/operators.cpp		 	\
			Machine/Cursynth/mono_panner.cpp	 	\
			Machine/Cursynth/midi_lookup.cpp	 	\
			Machine/Cursynth/linear_slope.cpp	 	\
			Machine/Cursynth/filter.cpp		 	\
			Machine/Cursynth/feedback.cpp		 	\
			Machine/Cursynth/envelope.cpp		 	\
			Machine/Cursynth/delay.cpp		 	\
			Machine/Cursynth/cursynth_strings.cpp	 	\
			Machine/Cursynth/cursynth_engine.cpp	 	\
			Machine/Cursynth/wave.cpp		 	\
			Machine/Cursynth/voice_handler.cpp	 	\
			Machine/Cursynth/value.cpp		 	\
			Machine/Cursynth/trigger_operators.cpp	 	\
			Machine/Cursynth/step_generator.cpp	 	\
			Machine/Cursynth/smooth_value.cpp	 	\
			Machine/Cursynth/smooth_filter.cpp	 	\
			Machine/Cursynth/send_receive.cpp	 	\
			Machine/Open303/Open303Machine.cpp	 \
			Machine/Open303/rosic_Open303.cpp		 \
			Machine/Open303/Open303UserInterface.cpp	 \
			Machine/Open303/rosic_MidiNoteEvent.cpp	 \
			Machine/Open303/rosic_AcidSequencer.cpp	 \
			Machine/Open303/rosic_Complex.cpp		 \
			Machine/Open303/rosic_AcidPattern.cpp	 \
			Machine/Open303/rosic_BlendOscillator.cpp	 \
			Machine/Open303/rosic_OnePoleFilter.cpp	 \
			Machine/Open303/rosic_NumberManipulations.cpp	\
			Machine/Open303/rosic_FourierTransformerRadix2.cpp\
			Machine/Open303/rosic_DecayEnvelope.cpp	\
			Machine/Open303/rosic_MipMappedWaveTable.cpp	\
			Machine/Open303/rosic_BiquadFilter.cpp		\
			Machine/Open303/GlobalFunctions.cpp		\
			Machine/Open303/rosic_AnalogEnvelope.cpp		\
			Machine/Open303/rosic_TeeBeeFilter.cpp		\
			Machine/Open303/rosic_LeakyIntegrator.cpp		\
			Machine/Open303/rosic_FunctionTemplates.cpp	\
			Machine/Open303/rosic_EllipticQuarterBandFilter.cpp\
			Machine/Open303/rosic_RealFunctions.cpp		\
			Machine/Twytch/TwytchsynthMachine.cpp		\
			Machine/Twytch/TwytchsynthUserInterface.cpp	\
			Machine/Twytch/twytch_alias.cpp				\
			Machine/Twytch/twytch_arpeggiator.cpp			\
			Machine/Twytch/twytch_bypass_router.cpp			\
			Machine/Twytch/twytch_bit_crush.cpp			\
			Machine/Twytch/twytch_fixed_point_oscillator.cpp		\
			Machine/Twytch/twytch_filter.cpp				\
			Machine/Twytch/twytch_feedback.cpp			\
			Machine/Twytch/twytch_envelope.cpp			\
			Machine/Twytch/twytch_distortion.cpp			\
			Machine/Twytch/twytch_delay.cpp				\
			Machine/Twytch/twytch_helm_lfo.cpp			\
			Machine/Twytch/twytch_helm_engine.cpp			\
			Machine/Twytch/twytch_helm_common.cpp			\
			Machine/Twytch/twytch_formant_manager.cpp		\
			Machine/Twytch/twytch_fixed_point_wave.cpp		\
			Machine/Twytch/twytch_helm_voice_handler.cpp		\
			Machine/Twytch/twytch_helm_oscillators.cpp		\
			Machine/Twytch/twytch_helm_module.cpp			\
			Machine/Twytch/twytch_operators.cpp			\
			Machine/Twytch/twytch_noise_oscillator.cpp		\
			Machine/Twytch/twytch_mono_panner.cpp			\
			Machine/Twytch/twytch_midi_lookup.cpp			\
			Machine/Twytch/twytch_memory.cpp				\
			Machine/Twytch/twytch_magnitude_lookup.cpp		\
			Machine/Twytch/twytch_linear_slope.cpp			\
			Machine/Twytch/twytch_processor_router.cpp		\
			Machine/Twytch/twytch_processor.cpp			\
			Machine/Twytch/twytch_phaser.cpp				\
			Machine/Twytch/twytch_oscillator.cpp			\
			Machine/Twytch/twytch_reverb_comb.cpp			\
			Machine/Twytch/twytch_reverb_all_pass.cpp		\
			Machine/Twytch/twytch_reverb.cpp				\
			Machine/Twytch/twytch_resonance_lookup.cpp		\
			Machine/Twytch/twytch_resonance_cancel.cpp		\
			Machine/Twytch/twytch_value.cpp				\
			Machine/Twytch/twytch_trigger_operators.cpp		\
			Machine/Twytch/twytch_switch.cpp				\
			Machine/Twytch/twytch_stutter.cpp			\
			Machine/Twytch/twytch_step_generator.cpp			\
			Machine/Twytch/twytch_smooth_value.cpp			\
			Machine/Twytch/twytch_smooth_filter.cpp			\
			Machine/Twytch/twytch_simple_delay.cpp			\
			Machine/Twytch/twytch_wave.cpp				\
			Machine/Twytch/twytch_voice_handler.cpp			\
			Machine/Twytch/twytch_detune_lookup.cpp			\
			Machine/Twytch/twytch_sample_decay_lookup.cpp		\
			Machine/Twytch/twytch_portamento_slope.cpp		\
			Machine/Twytch/twytch_dc_filter.cpp			\
			Machine/MidiOutSystem/MidiOutUserInterface.cpp            \
			Machine/MidiOutSystem/MidiOutMachine.cpp                  \
			Machine/MDADrum/MDADrumMachine.cpp			\
			Machine/MDADrum/MDADrumUserInterface.cpp			\
			Machine/MDADrum/drumsynth.cpp				\
			Machine/MDADrum/profport.cpp				








#OBJTOLINK=RtAudio.o

#SOURCES=Machine.cpp  AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp SineOscillator.cpp SawOscillator.cpp  FuzzyPulseOscillator.cpp PulseOscillator.cpp  TriangleOscillator.cpp WaveTableSineOscillator.cpp NoiseOscillator.cpp OneOscillator.cpp MonoMixer.cpp ADSR.cpp SDL_GUI.cpp VCO.cpp Sequencer.cpp InputManager.cpp Biquad.cpp PatternSequencer.cpp  AudioDriverSDL.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp Effect.cpp EffectDelay.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=PatternPlayer_SDL.exe

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJTOLINK)  $(OBJECTS) -o $@ $(LDFLAGS)
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
