CC=g++
CC=/opt/opendingux-toolchain/usr/bin/mipsel-linux-g++
CC=/opt/gcw0-toolchain/usr/bin/mipsel-gcw0-linux-uclibc-g++


CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb -pg
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o  
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o   

CFLAGS=-c -DLINUX -I. -LSDL/lib
CFLAGS=-c -O3 -DLINUX -D__RTAUDIO__ -DOPENDINGUX -I. -I/opt/opendingux-toolchain/usr/include/ -L/opt/opendingux-toolchain/usr/lib/ -lSDL -lSDL_ttf -fpermissive -DFIXED -fno-rtti -fomit-frame-pointer -ffunction-sections -ffast-math -fsingle-precision-constant -G0
CFLAGS=-c -O3 -DLINUX -D__RTAUDIO__ -DOPENDINGUX -I. -Iopt/gcw0-toolchain/usr/include/ -Lopt/gcw0-toolchain/usr/lib -lSDL -lSDL_ttf -fpermissive -DFIXED -fno-rtti -fomit-frame-pointer -ffunction-sections -ffast-math -fsingle-precision-constant -G0

LDFLAGS=-Lopt/gcw0-toolchain/usr/lib -lasound -lSDL -lSDL_gfx -lSDL_ttf -lpthread  RtAudio.o -DFIXED 
#SOURCES=Machine.cpp  AudioMixer.cpp AudioEngine.cpp PatternElement.cpp Pattern.cpp PatternPlayer.cpp PatternReader.cpp Oscillator.cpp  MonoMixer.cpp ADSR.cpp SDL_GUI.cpp InputManager.cpp VCO.cpp Sequencer.cpp OneOscillator.cpp Biquad.cpp PatternSequencer.cpp AudioDriverRTAudio.cpp PicosynthMachine.cpp  PicodrumMachine.cpp dbopl/dbopl.cpp dbopl/hiopl.cpp DboplMachine.cpp Filter.cpp AMSynthLowPassFilter.cpp  Effect.cpp EffectDelay.cpp SongSequencer.cpp WaveTableManager.cpp WaveTable.cpp Generator.cpp 


SOURCES=PatternPlayer.cpp \
		      SDL_GUI.cpp              \
		      SYSTEMLINUX.cpp          \
		      AudioEngine.cpp          \
		      AudioDriverRTAudio.cpp   \
		      Instrument.cpp           \
		      Synth.cpp                \
		      Oscillator.cpp           \
		      OneOscillator.cpp        \
		      Biquad.cpp               \
		      AudioMixer.cpp           \
		      Wave.cpp        \
		      Machine.cpp              \
		      MonoMixer.cpp            \
		      InputManager.cpp         \
		      Filter.cpp               \
		      AMSynthLowPassFilter.cpp \
		      Effect.cpp               \
		      EffectDelay.cpp          \
		      EffectDisabled.cpp       \
		      WaveTableManager.cpp     \
		      WaveTable.cpp            \
		      Generator.cpp            \
		      PatternElement.cpp       \
		      Pattern.cpp              \
		      PatternReader.cpp        \
		      Sequencer.cpp            \
		      PatternSequencer.cpp     \
		      SongSequencer.cpp        \
		      NoteFreq.cpp             \
		      PitchBend.cpp            \
		      TweakableKnob.cpp        \
		      UserInterface.cpp	       \
		      Machine/Picosynth/PicosynthUserInterface.cpp \
		      Machine/Picosynth/PicosynthADSR.cpp        \
		      Machine/Picosynth/PicosynthVCO.cpp         \
		      Machine/Picosynth/PicosynthMachine.cpp     \
		      Machine/Picodrum/PicodrumUserInterface.cpp \
		      Machine/Picodrum/PicodrumVCO.cpp           \
		      Machine/Picodrum/PicodrumADSR.cpp          \
		      Machine/Picodrum/PicodrumMachine.cpp       \
		      Machine/Dbopl/DboplUserInterface.cpp       \
		      Machine/Dbopl/dbopl.cpp                    \
		      Machine/Dbopl/hiopl.cpp                    \
		      Machine/Dbopl/DboplMachine.cpp             \
		      Machine/PBSynth/PBSynthUserInterface.cpp   \
		      Machine/PBSynth/synthengine.cpp            \
		      Machine/PBSynth/osc.cpp                    \
		      Machine/PBSynth/lfo.cpp                    \
		      Machine/PBSynth/filter.cpp                 \
		      Machine/PBSynth/env.cpp                    \
		      Machine/PBSynth/echo.cpp                   \
		      Machine/PBSynth/osctab.cpp                 \
		      Machine/PBSynth/lfotab.cpp                 \
		      Machine/PBSynth/envtab.cpp                 \
		      Machine/PBSynth/coeff.cpp                  \
		      Machine/PBSynth/PBSynthMachine.cpp         \



OBJECTS=$(SOURCES:.cpp=.o)
DEPENDENCY=$(SOURCES:.cpp=.d)
EXECUTABLE=PatternPlayer.gcw

all: $(SOURCES) $(DEPENDENCY) $(EXECUTABLE) 

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@


%.o : %.cpp 
	$(CC) $(CFLAGS) $< -o $@

# include all the dependency .d file into the makefile 
# it allow to match change in .h file
include ${DEPENDENCY}

# the .d file contain the dependency
%.d : %.cpp %.h
	$(CC) -I. -MM $< -o $@


# SYSTEMLINUX.d does have a .h which is SYSTEM.h, so it need a tweaks
SYSTEMLINUX.d:SYSTEMLINUX.cpp 
	$(CC) -I. -MM $< -o $@ 

# systemlinux.d does have a .h which is system.h
PatternPlayer.d:PatternPlayer.cpp
	$(CC) -I. -MM $< -o $@ 



clean:
	-rm -f $(OBJECTS) 
	-rm -f $(EXECUTABLE)
	-rm -f $(DEPENDENCY)
