CC=g++
CFLAGS=-c -DLINUX -I. -LSDL/lib -g
CFLAGS=-O3 -Wall -I.. -DHAVE_GETTIMEOFDAY -D__LINUX_ALSA__
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf
SOURCES=RtAudio.cpp
OBJDIR=debian
OBJECTS=$(SOURCES:.cpp=.o)
OBJECTSINOBJDIR    = $(addprefix $(OBJDIR)/,$(OBJECTS))


all: $(OBJECTSINOBJDIR)

$(OBJDIR)/%.o : %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	-rm -f $(OBJECTSINOBJDIR)
