CC=g++
CFLAGS=-c -DLINUX_DESKTOP -DLINUX -I. -LSDL/lib -g -D__SDL12__ -DPC_DESKTOP
LDFLAGS=-lSDL -lSDL_gfx -lSDL_ttf
SOURCES=Picoloop.cpp SDL_GUI.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=Picoloop

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
