CC=g++
CC=/opt/opendingux-toolchain/usr/bin/mipsel-linux-g++
CFLAGS=-c -DLINUX -I. -LSDL/lib -ggdb 
CFLAGS=-c -DLINUX -I. -I/opt/opendingux-toolchain/usr/include/ -L/opt/opendingux-toolchain/usr/lib/ -lSDL -lSDL_ttf
LDFLAGS=-lSDL -lSDL_ttf
SOURCES=InputManager.cpp SDL_GUI.cpp InputTest.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=InputTest

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
