#ifndef __MASTER____
#define __MASTER____
#include <SDL/SDL.h>

#define DEFAULTFREQ      44100
#define DEFAULTSAMPLES   2048
#define DEFAULTCHANNELS  2
#define DEFAULTPOLYPHONY 16
#define DEFAULTFORMAT    AUDIO_S16

#define SCREEN_WIDTH	640
#define SCREEN_HEIGHT	480
#define SCREEN_DEPTH	16
#define WAVETABLE_SIZE  1024*16
#define FPU 0

#define MAX_PATTERN_BY_PROJECT 64


#define TRACK_MAX 1

#define BUFFER_FRAME DEFAULTSAMPLES
//#define DEFAULT_FREQ 44100


#endif
